// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gcpdiscoveryMock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tripod-networks/wireguard-gateway-operator/internal/gcpdiscovery"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockClient
func (_mock *MockClient) List(ctx context.Context, project string, region string, mig string, recorded []gcpdiscovery.Recorded, refreshNames []string) (gcpdiscovery.Snapshot, error) {
	ret := _mock.Called(ctx, project, region, mig, recorded, refreshNames)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 gcpdiscovery.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []gcpdiscovery.Recorded, []string) (gcpdiscovery.Snapshot, error)); ok {
		return returnFunc(ctx, project, region, mig, recorded, refreshNames)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []gcpdiscovery.Recorded, []string) gcpdiscovery.Snapshot); ok {
		r0 = returnFunc(ctx, project, region, mig, recorded, refreshNames)
	} else {
		r0 = ret.Get(0).(gcpdiscovery.Snapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, []gcpdiscovery.Recorded, []string) error); ok {
		r1 = returnFunc(ctx, project, region, mig, recorded, refreshNames)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - project string
//   - region string
//   - mig string
//   - recorded []gcpdiscovery.Recorded
//   - refreshNames []string
func (_e *MockClient_Expecter) List(ctx any, project any, region any, mig any, recorded any, refreshNames any) *MockClient_List_Call {
	return &MockClient_List_Call{Call: _e.mock.On("List", ctx, project, region, mig, recorded, refreshNames)}
}

func (_c *MockClient_List_Call) Run(run func(ctx context.Context, project string, region string, mig string, recorded []gcpdiscovery.Recorded, refreshNames []string)) *MockClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []gcpdiscovery.Recorded
		if args[4] != nil {
			arg4 = args[4].([]gcpdiscovery.Recorded)
		}
		var arg5 []string
		if args[5] != nil {
			arg5 = args[5].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_List_Call) Return(snapshot gcpdiscovery.Snapshot, err error) *MockClient_List_Call {
	_c.Call.Return(snapshot, err)
	return _c
}

func (_c *MockClient_List_Call) RunAndReturn(run func(ctx context.Context, project string, region string, mig string, recorded []gcpdiscovery.Recorded, refreshNames []string) (gcpdiscovery.Snapshot, error)) *MockClient_List_Call {
	_c.Call.Return(run)
	return _c
}
